language: python
sudo: false

python:
  - 3.4

before_script:
  - pip install tox

script: tox

env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=py27-flake8
    - TOXENV=py34-flake8

notifications:
  on_success: change
  on_failure: always
